name: Build CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v4
    - name: Install compiler
      run: sudo apt-get update && sudo apt-get install -y ${{ matrix.compiler }}
    - name: Build
      run: make CC=${{ matrix.compiler }}
